### PR TITLE
Add documentation to give comparison of dataframes

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by heronshoes** [comment]
I think this will be a good table for users!

**Comment by heronshoes** [comment]
I corrected `pandas`.
And updated as more generally description for Join. 
Thanks!

**Comment by bkmgit** [comment]
Thanks. Will update the Fedora CI. Can you assign https://github.com/heronshoes/red_amber/issues/187 to me?

**Comment by heronshoes** [comment]
Arrow 11.0.0 gem has released. CI issue has gone. I will merge this.

Later I will make a link to this file in README.md .
Thanks!

**Pull request merged**
