### PR TITLE
Add installation for Fedora

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by bkmgit** [comment]
Based on https://github.com/heronshoes/red_amber/issues/41

Working on for [Sotware Collection](https://www.softwarecollections.org) for Fedora which maybe easier to use than standard package manager.

**Comment by heronshoes** [comment]
Information for Fedora is helpful. Also adding `gem install ...` should be better for users.
Thanks!

**Comment by bkmgit** [comment]
Welcome. Can you try to rerun failing test? It does not seem to be related to changes in README.  Can also add a test based on Fedora Rawhide using [podman](https://podman.io/).

**Comment by heronshoes** [comment]
Something is wrong in test coverage in check. Re-run didn't work. "Resource not accessible by integration" error is happening. I will check permissions in setting.

**Pull request closed without merging**
