### PR TITLE
Update Doc

### PR DESCRIPTION
**Pull request by kojix2**
- loading csv without headers

### CODE REVIEW

**Comment by kojix2** [comment]
Would you prefer to use symbols instead of strings?

  ```ruby
  RedAmber::DataFrame.load("test/entity/without_header.csv", headers: [:a, :b, :c])
  ```

**Comment by heronshoes** [comment]
Thanks!
I prefer Symbols to Strings. Symbols will be better in this case. But I will not force Symbols anytime for example when it is :"untara-kantara" ("untara-kantara" is OK).

RedAmber will automatically change them to Symbols.

Can you set commit message like this ?
`git commit --amend -m ':memo: Update DataFrame.md about loading csv without headers'

**Comment by heronshoes** [comment]
Test on macos is failing. (due to error in homebrew?)

I will re-run the test in a while, so please make the change.

**Comment by kojix2** [comment]
Thanks. Changed to symbols. 
Why not rewrite the commit message with a squash merge?

**Comment by heronshoes** [comment]
OK. I will use squash. Thank you.

**Comment by kojix2** [comment]
Thank you.
I know many people will be sending pull requests in the future, and if you want to leave a clean commit message, squash is the way to go.

**Comment by kojix2** [comment]
Thanks!

**Pull request merged**
